spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/oneMicr
    username: postgres
    password: Andy1964
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5433/oneMicr
    user: postgres
    password: Andy1964
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
